### ISSUE TITLE
Repeated cron backup jobs

### ISSUE THREAD

**Issue by xmik** [sameersbn/docker-gitlab#1121]
Hi, we've been using `sameersbn/gitlab:8.12.5` docker image for a while and noticed this (run inside a container):
```
root@2ecfcd1201cb:/home/git/gitlab# head /var/spool/cron/crontabs/git        
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/cron.git installed on Sat Mar 11 10:25:46 2017)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
00 23 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 23 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 23 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
root@2ecfcd1201cb:/home/git/gitlab# cat /var/spool/cron/crontabs/git | wc -l
120
```
~120 lines of backup jobs. I believe it was configured on each container start?

Besides that, thank you for maintaining gitlab docker image :) .

**Comment by QuickJack** [comment]
I can confirm this. I do have 5 identical entries in my crontab.

**Comment by solidnerd** [comment]
Hey,
I guess it's fixed in some versions higher than yours. I would recommend to use the latest version.

**Comment by QuickJack** [comment]
I am using 8.16.6. The 8.17 version isn't ready yet. So I guess, there isn't a viable solution to this problem.

**Comment by QuickJack** [comment]
My 8.17.4 container is still showing 4 identical entries in /var/spool/cron/crontabs/git

**Comment by QuickJack** [comment]
Still present in 9.4.5. This problem is really annoying as it could lead to server crashes because of filled hard discs. Please review the proposed solution.
